name: Compile Firmware

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  compile-arduino:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Remote Arduino Nano ESP32
            fqbn: arduino:esp32:nano_nora
            sketch: firmware/remote_espnow

          - name: Dongle ESP32-C3
            fqbn: esp32:esp32:esp32c3
            sketch: firmware/dongle_espnow_bridge

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile ${{ matrix.name }}
        uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: arduino:esp32
            - name: esp32:esp32
              source-url: https://espressif.github.io/arduino-esp32/package_esp32_index.json
          sketch-paths: |
            - ${{ matrix.sketch }}
          libraries: |
            - name: U8g2

  check-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Check Python syntax
        run: |
          python -m py_compile firmware/raspberry-pi/music_controller.py